"""Add is_favorite to books

Revision ID: 9e8b89d72de8
Revises: ed20f8775b5f
Create Date: 2025-01-11 13:53:15.105278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8b89d72de8'
down_revision: Union[str, None] = 'ed20f8775b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'is_favorite')
    # ### end Alembic commands ###
